---
title: "Code Book"
author: "Kathedra Burton"
date: "January 21, 2016"
output: html_document
---

This code book describes data found in the dataset *tidydata.txt*.  The raw data is available here [Raw Data](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip).

The data has been treated with the script in run_analysis.R. 

## Identifiers
* subject: subject id no.
* activity_number: links to particular activity

## Measurements

* subject
* activity
* activity_number
* timeBodyAcceleration-mean()-X
* timeBodyAcceleration-mean()-Y
* timeBodyAcceleration-mean()-Z
* timeBodyAcceleration-std()-X
* timeBodyAcceleration-std()-Y
* timeBodyAcceleration-std()-Z
* timeGravityAcceleration-mean()-X
* timeGravityAcceleration-mean()-Y
* timeGravityAcceleration-mean()-Z
* timeGravityAcceleration-std()-X
* timeGravityAcceleration-std()-Y
* timeGravityAcceleration-std()-Z
* timeBodyAccelerationJerk-mean()-X
* timeBodyAccelerationJerk-mean()-Y
* timeBodyAccelerationJerk-mean()-Z
* timeBodyAccelerationJerk-std()-X
* timeBodyAccelerationJerk-std()-Y
* timeBodyAccelerationJerk-std()-Z
* timeBodyGyroscope-mean()-X
* timeBodyGyroscope-mean()-Y
* timeBodyGyroscope-mean()-Z
* timeBodyGyroscope-std()-X
* timeBodyGyroscope-std()-Y
* timeBodyGyroscope-std()-Z
* timeBodyGyroscopeJerk-mean()-X
* timeBodyGyroscopeJerk-mean()-Y
* timeBodyGyroscopeJerk-mean()-Z
* timeBodyGyroscopeJerk-std()-X
* timeBodyGyroscopeJerk-std()-Y
* timeBodyGyroscopeJerk-std()-Z
* timeBodyAccelerationMagnitude-mean()
* timeBodyAccelerationMagnitude-std()
* timeGravityAccelerationMagnitude-mean()
* timeGravityAccelerationMagnitude-std()
* timeBodyAccelerationJerkMagnitude-mean()
* timeBodyAccelerationJerkMagnitude-std()
* timeBodyGyroscopeMagnitude-mean()
* timeBodyGyroscopeMagnitude-std()
* timeBodyGyroscopeJerkMagnitude-mean()
* timeBodyGyroscopeJerkMagnitude-std()
* frequencyBodyAcceleration-mean()-X
* frequencyBodyAcceleration-mean()-Y
* frequencyBodyAcceleration-mean()-Z
* frequencyBodyAcceleration-std()-X
* frequencyBodyAcceleration-std()-Y
* frequencyBodyAcceleration-std()-Z
* frequencyBodyAccelerationJerk-mean()-X
* frequencyBodyAccelerationJerk-mean()-Y
* frequencyBodyAccelerationJerk-mean()-Z
* frequencyBodyAccelerationJerk-std()-X
* frequencyBodyAccelerationJerk-std()-Y
* frequencyBodyAccelerationJerk-std()-Z
* frequencyBodyGyroscope-mean()-X
* frequencyBodyGyroscope-mean()-Y
* frequencyBodyGyroscope-mean()-Z
* frequencyBodyGyroscope-std()-X
* frequencyBodyGyroscope-std()-Y
* frequencyBodyGyroscope-std()-Z
* frequencyBodyAccelerationMagnitude-mean()
* frequencyBodyAccelerationMagnitude-std()
* frequencyBodyAccelerationJerkMagnitude-mean()
* frequencyBodyAccelerationJerkMagnitude-std()
* frequencyBodyGyroscopeMagnitude-mean()
* frequencyBodyGyroscopeMagnitude-std()
* frequencyBodyGyroscopeJerkMagnitude-mean()
* frequencyBodyGyroscopeJerkMagnitude-std()


##Activities

* WALKING (1): subject walking during the test
* WALKING UPSTAIRS (2): subject walking up stairs
* WALKING DOWNSTAIRS (3): subject walking down stairs
* SITTING (4): subject sitting during the test
* STANDING (5): subject standing during the test
* LAYING (6): subject laying down during the test


